### ISSUE TITLE
I have some trouble with parsing in 4.0.2

### ISSUE THREAD

**Issue by AFSlayer** [SBJson/SBJson#215]
I parsed following data : 
`{"rc":"0","rm":"OK","pi":{"tc":0,"rp":0},"rs":{"c":0}"}`

You can recognize that there is some syntax error at the end of the value. (key is rs)
It supposed to be handling by error handler but SBJason4 doesn't check the error and doesn't return complete or error status. 

```
       SBJson4ValueBlock block = ^(id v, BOOL *stop) {
                  // not here
         };

        SBJson4ErrorBlock eh = ^(NSError* err) {
                 // not here too
        };

        id parser = [SBJson4Parser multiRootParserWithBlock:block
                                               errorHandler:eh];

        // DATA encoded by base64Encode
        [parser parse:[NSData dataWithBase64EncodedString:@"eyJyYyI6IjAiLCJybSI6Ik9LIiwicGkiOnsidGMiOjAsInJwIjowfSwicnMiOnsiYyI6MH0ifQ=="]];
```

does anyone who faced with this issue?
asap please

**Comment by stig** [comment]
Thanks for the bug report! I am afraid I haven't had a chance to look at
this yet. It would be a lot easier for me to look into if you managed to
add a failing test case to the existing test framework!

**Comment by stig** [comment]
Hi @AFSlayer,

Sorry about the time to get back to you. I cannot reproduce the issue, I'm afraid. I added your broken JSON to my test suite in https://github.com/stig/json-framework/pull/221 and it is correctly reported as an error for me. Can you please share more details about how this occurs for you?

Stig

**Comment by stig** [comment]
I believe this is probably due to broken UTF8. There was a complete overhaul of the UTF8 validation in v4.0.4, so as I cannot reproduce this I'm going to assume it was fixed there. If you can reproduce this crash with the latest v4 release (v4.0.5 at the time of writing) then please re-open this issue or create a new one!

**Comment by AFSlayer** [comment]
우리는 이제 시스템에서 제공해주는 파서를 쓰기로 했습니다
[NSJSONSerialization JSONObjectWithData:options:error:];
관심가져주셔서 고맙습니다

**Comment by AFSlayer** [comment]
environment:

os x 10.12.4
xcode Version 8.3.2 (8E2002)
SBJson 4.0.5

Sorry, but it still doesn't work. I can't catch the callback to **SBJson4ValueBlock** and **SBJson4ErrorBlock**.


If there is double quotation mark ( " ) before last close brace ( } ) then can not parse and not occur error neither. 

and I tried also following code but it occurs same result. 

```
[parser parse:[@"{\"rc\":\"0\",\"rm\":\"OK\",\"pi\":{\"tc\":0,\"rp\":0},\"rs\":{\"c\":0}\"}" dataUsingEncoding:NSUTF8StringEncoding]];
```

I attached code and console log screenshot. 

![2017-08-30 11 40 22](https://user-images.githubusercontent.com/5547818/29852992-378f2e4e-8d78-11e7-9150-ae43fb9693c1.png)
![2017-08-30 11 40 26](https://user-images.githubusercontent.com/5547818/29852995-3a1e0dce-8d78-11e7-9853-65d721387d19.png)

**Comment by AFSlayer** [comment]
JARANARA MEORIMEORI..

**Comment by stig** [comment]
Thank you for the updated bug report. I'll re-open the ticket and try to schedule some time to look into it.

**Comment by stig** [comment]
I've had another go, but I still can't reproduce it in SBJson 5. I'm going to close this, sorry.
